[package]
name = "sudoku-www"
version = "0.1.0"
authors = ["Yrjan Skrimstad <yrjans@gmail.com>"]
edition = "2018"
license = "MIT"


[lib]
crate-type = ["cdylib"]


[dependencies]
seed = "^0.3.3"
wasm-bindgen = "^0.2.42"
web-sys = "^0.3.19"
